base_path: "."
preserve_hierarchy: true

files:
  - source: 'app/translations/ts/en_US.ts'
    translation: 'app/translations/ts/%two_letters_code%_%country_code%.ts'
    languages_mapping:
      two_letters_code:
        de: de
        es: es
        fr: fr
        it: it
        ja: ja
        ko: ko
        pl: pl
        pt: pt
        ru: ru
        tr: tr
        zh: zh
      country_code:
        de: DE
        es: MX
        fr: FR
        it: IT
        ja: JP
        ko: KR
        pl: PL
        pt: BR
        ru: RU
        tr: TR
        zh: CN
