base_path: "."
preserve_hierarchy: true

files:
  - source: 'app/translations/ts/en_US.ts'
    translation: 'app/translations/ts/%two_letters_code%_%country_code%.ts'
    languages_mapping:
      two_letters_code:
        de: de
        es: es
        fr: fr
        it: it
        ja: ja
        ko: ko
        pl: pl
        pt: pt
        ru: ru
        tr: tr
        zh: zh
      country_code:
        DE: de
        MX: es
        FR: fr
        IT: it
        JP: ja
        KR: ko
        PL: pl
        BR: pt
        RU: ru
        TR: tr
        CN: zh
