base_path: "."
preserve_hierarchy: true

files:
  - source: 'app/translations/ts/en_US.ts'
    translation: 'app/translations/ts/%locale%.ts'
    languages_mapping:
      locale:
        de: de_DE
        es-MX: es_MX
        fr: fr_FR
        it: it_IT
        ja: ja_JP
        ko: ko_KR
        pl: pl_PL
        pt-BR: pt_BR
        ru: ru_RU
        tr: tr_TR
        zh-CN: zh_CN
