name: Crowdin Sync

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync translations with Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n/crowdin-translations
          create_pull_request: false
          config: 'crowdin.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: l10n/crowdin-translations
          title: 'chore(i18n): update Crowdin translations'
          body: |
            This PR updates .ts translation files from Crowdin
            and recompiles the .qm files using Qt 6 tools.
          commit-message: 'chore(i18n): update translations and .qm files'
          base: main
